<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MockCommerce</RootNamespace>
  </PropertyGroup>


  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MockCommerce.Tests" />
  </ItemGroup>
</Project>
